// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ProductID   int64              `json:"product_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	PriceCents  pgtype.Int4        `json:"price_cents"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	UserID       int64              `json:"user_id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordSalt string             `json:"password_salt"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
